-- Alta inicial de familias (generado desde public/list/familias_links.csv)
-- Requiere haber corrido antes supabase/schema.sql (crea la tabla).
alter table public.familias add column if not exists seccion text;
insert into public.familias (nombre, pases, token, seccion) values
  ('Ing. Osvaldo Osuna Santos y esposa', 2, 'rDMZNEqi0w', 'Principal'),
  ('Ing. Joel González Alonso y familia', 4, '3gy5O2bCth', 'Principal'),
  ('Sr. Bonifilio Mazariegos Roblero y esposa', 2, 'T4eudx0tzs', 'Principal'),
  ('Sr. Abidan Mazariegos Laparra y familia', 4, '6tDzDvek1H', 'Principal'),
  ('Sr. Binifilio Mazariegos Laparra y familia', 3, 'UoCizAAxJz', 'Principal'),
  ('Ing. Kenni Mazariegos Laparra y familia', 4, 'X1lRByoYCB', 'Principal'),
  ('Mv. Weslin Mazariegos Laparra y Sra.', 2, 'OBwWOIyYzd', 'Principal'),
  ('Señorita Rosita Rodríguez Laparra', 2, 'PlrjbNkh4E', 'Principal'),
  ('Ing. Alfredo Pineda y esposa', 2, 'gCy6KrXCqe', 'Principal'),
  ('Sra. Irma Cruz Guiron', 2, 'C73Tre1Mud', 'Principal'),
  ('Sr. Alan Mazariegos Laparra y esposa', 2, 'DdiXYY9Svu', 'Principal'),
  ('Sra. Ana María Rabanales Cardona', 2, 'Mrs83nV09j', 'Principal'),
  ('Sra. Nandy Báez Barrios y familia', 3, 'hX9xKp6fYn', 'Principal'),
  ('Sra. Martha González Aquino', 2, 'a69Kt4bGN5', 'Principal'),
  ('Sr. Abel Ramírez González y familia', 4, 'rZg1ibXkrF', 'Principal'),
  ('Sr. Wualter Giovanni González Hernández y Sra.', 2, 'fvXAGSoBtT', 'Principal'),
  ('Sr. Héctor Flores Evangelista y esposa', 2, 'HFlBGFnQXM', 'Principal'),
  ('Dr. Edgar Pérez Reyes y familia', 5, 'Z9K4Xsac3H', 'Principal'),
  ('Ing. Osvaldo Osuna Laparra y Sra.', 2, 'jQ7znXV56S', 'Principal'),
  ('Sr. Jorge Miguel Sánchez Laparra y Sra.', 2, 'voBHCgsqeK', 'Principal'),
  ('Señorita María Del Rosario Mateo Santiago', 2, 'TzJHEWzkGz', 'Principal'),
  ('Lic. Bonifacio Hernández Gómez y esposa', 2, '7drVhMSkew', 'Principal'),
  ('Sra. Everilda Escalante Roblero y familia', 3, 'TWatN7FGOl', 'Principal'),
  ('Sra. Rosita Borras Rodas', 2, 'Eh4bYtu1k9', 'Principal'),
  ('Sr. Noe Ramírez Cruz y esposa', 2, 'D7WGx6S0rN', 'Principal'),
  ('Lic. Amadeo Vázquez Cruz y esposa', 2, '7MGB81cXMY', 'Principal'),
  ('Lic. Fernando Laparra Barrios y familia', 5, 'gkb4QbkVcF', 'Principal'),
  ('Mvz. Rodolfo Otilio Briones Rodas y Sra.', 2, 'Cjrdg9SI7B', 'Principal'),
  ('Profesora Sandra Luz Domínguez Zea y familia', 4, 'yTMg9s4xPC', 'Principal'),
  ('Sr. Juan Carlos Suarez Soto y familia', 4, 'EyzUyLUWaW', 'Principal'),
  ('Sr. Miguel Ángel Sánchez Pérez y Sra.', 2, 'xSNawnWZQP', 'Principal'),
  ('Profesor Ramiro Avendaño Vidal y esposa', 2, 'CcyEo5RisA', 'Principal'),
  ('Sr. Manuel Antonio Cordero Muñoz y esposa', 2, 'L5TGeNpvu4', 'Principal'),
  ('Profesora Maricela González Roblero', 1, '0SXiTifbmF', 'Principal'),
  ('Sra. Concepción Fidalma González Roblero', 1, '8HjKHnunt2', 'Principal'),
  ('Ing. Jesús Imanol Castillo Avendaño', 2, 'ZAoaeawiXB', 'Principal'),
  ('Profesora Dulce Lilia Osuna Santos', 2, 'lWagFMRb9U', 'Principal'),
  ('Ing. Joaquín Guadalupe Cruz Torres', 1, 'FMdsZHUNod', 'Principal'),
  ('Contador Oscar Ozuna Santos', 2, 'rxQh2nH7pf', 'Principal'),
  ('Lic. Julio Cesar Ozuna Santos y familia', 5, 'f3btibLGPi', 'Principal'),
  ('Sr. Luis Alberto Sánchez y familia', 4, '0kOqBK0EKc', 'Principal'),
  ('Sra. Margarita Laparra Barrios', 1, 'L4S2B5pVnS', 'Principal'),
  ('Sr. Roberto Carlos Monje y familia', 5, 'hbw88bqZgA', 'Principal'),
  ('Ing. Christian Baez Laparra y familia', 4, 'TNy7QiBOk8', 'Principal'),
  ('Sra. María Del Rosario Ozuna Santos', 1, 'lfqKri4n8l', 'Principal'),
  ('Lic. Oscar Osuna Saldivar y familia', 5, 'dUNlo6VV8A', 'Principal'),
  ('Sr. Gerardo Cruz Perez y familia', 4, 'X5IdvMGcBn', 'Principal'),
  ('Sr. Sergio Morales Ozuna y familia', 4, 'JalnhUOjNR', 'Principal'),
  ('Lic. Efrain Antonio Torres Cortes y esposa', 2, 'SqiHdZVFCP', 'Principal'),
  ('Lic. Ervin Anibal Ozuna Becerra y Sra.', 2, '64FdlTZ63Q', 'Principal'),
  ('Ing. Pedro Coutiño Mundo', 2, 'XSY4WUnSHN', 'Principal'),
  ('Lic. Jesus Armando Moreno y Sra.', 2, 'ihzU3BOkSm', 'Principal'),
  ('Sra. Yesenia Soto Mendez y familia', 2, '7smMW3CZ8O', 'Principal'),
  ('Sr. Alfonso Ramírez y esposa', 2, 'QiL1uzYYkL', 'Principal'),
  ('Lic. Erwin Ramírez Molina y Sra.', 2, 'TKkqPnA3E8', 'Principal'),
  ('Ing. Davit Alfonso Ramírez Molina', 1, 'kQnsTRbRfq', 'Principal'),
  ('Lic. Ana Yuri Ramírez Molina', 2, 'JcSn2nMaVb', 'Principal'),
  ('Ing. Julián Sánchez Ozuna y esposa', 2, 'Fvw3mphRSP', 'Principal'),
  ('Lic. Guillermo Palafox Martínez y familia', 5, '6PlZNOPzWC', 'Principal'),
  ('Sra. Ana María Martínez y familia', 3, '4jQeURhqk1', 'Principal'),
  ('Contador Werclain Ozuna Santos', 4, 'sJthQXbyBP', 'Principal'),
  ('Lic. Gilberto Cortes Ozuna y familia', 4, 'nl4blmhDkG', 'Principal'),
  ('Lic. Alejandro Cortes Ozuna y familia', 4, 'nTb83pNJr3', 'Principal'),
  ('Lic. Francisco Santos Hernández', 4, 'yy42HNdKSa', 'Principal'),
  ('Profesor Serafín Ruíz Correa y familia', 4, 'pJrfZHOPQe', 'Principal'),
  ('Sr. Aldri Ruíz Ozuna y familia', 4, 'l5dUi6x8tt', 'Principal'),
  ('Lic. Cristhian Ruíz Ozuna y familia', 5, 'rmbGhYMBuo', 'Principal'),
  ('Sra. Aurora Hidalgo Matus', 2, 'rhHnl6LPzj', 'Principal'),
  ('Sr. Miguel Sánchez Laparra y Sra.', 2, 'ywkkCcVpWU', 'Principal'),
  ('Dra. Mirian Quiroz Reyes y familia', 2, 'q6KL1BzQR9', 'Principal'),
  ('Dra. Atziri Yaxiltun Cruz Ozuna', 2, 'ouYi3IUaKc', 'Principal'),
  ('Sra. Guadalupe Elizabeth Alonzo Castillejos', 1, '32wTTiEdFz', 'Principal'),
  ('Profesor Antonio Ruiz Guzman y esposa', 2, 'IWSHaiKyKo', 'Principal'),
  ('Lic. Abel Vargas y esposa', 2, 'QCLJisBPTR', 'Principal'),
  ('Sr. Rodrigo Flores y esposa', 2, 'xv8M4gsY2P', 'Principal'),
  ('Sra. Imelda Soto Méndez', 1, 'gyHARxCHbo', 'Principal'),
  ('Sra. Elena Soto Méndez', 1, 'FKr4MYSOBN', 'Principal'),
  ('Familia Mijangos Ozuna', 6, 've7gwNVSdu', 'Principal'),
  ('Ing. Guillermo De La Fuente Sánchez y familia', 4, 'Lm7GeTE92g', 'Principal'),
  ('Ing. Luan Roque y esposa', 2, 'V0Muj8e62P', 'Principal'),
  ('Sr. Mauricio Gama Esquinca y Sra.', 2, 'clVpuZsY3p', 'Principal'),
  ('Profesor Ever Ozuna Gordillo y familia', 4, 'NbX4gAuOn8', 'Principal'),
  ('Sr. Federico Ozuna Cancino y Sra.', 4, 'EGTSlrj18G', 'Principal'),
  ('Diana', 1, 'AGKobrAilj', 'Individual'),
  ('Avril', 1, 'InBDjE2Lv9', 'Individual'),
  ('Andrick', 1, 'RB0NfodWhD', 'Individual'),
  ('Valeria', 1, 'CdYG33KCGc', 'Individual'),
  ('Fernanda', 1, 'VBTCxwjJwt', 'Individual'),
  ('Andrea', 1, 'hHiPo1idmb', 'Individual'),
  ('Samantha', 1, 'K3EadCDMLS', 'Individual'),
  ('Levit', 1, '8BDYq2m3ub', 'Individual'),
  ('Valentina', 1, 'Z6EmYjZazG', 'Individual'),
  ('Matias', 1, 'HgUBkoIAZB', 'Individual'),
  ('Shasel', 1, '3jBx7fHZvC', 'Individual'),
  ('Virginia', 1, 'bqJntdjLqo', 'Individual'),
  ('Skarlett', 1, 'cKb7dqtLEL', 'Individual'),
  ('Yuriko', 1, 'q5lawhopnL', 'Individual'),
  ('Aracely', 1, 'Hq8cy6HXde', 'Individual'),
  ('Ivanna', 1, 'sHKehUVJPz', 'Individual'),
  ('Alina', 1, 'cUv4fjKOCx', 'Individual'),
  ('Gala', 1, 'MKgPSyY96S', 'Individual'),
  ('Cristian', 1, 'gTNiJ7Tgh5', 'Individual'),
  ('Alexa', 1, 'uYgtBwnT07', 'Individual'),
  ('Emily', 1, 'PABkYDYDmO', 'Individual'),
  ('Kenia', 1, 'pt4MVp7Wov', 'Individual'),
  ('Mayret', 1, '4KjYw1ZxSE', 'Individual'),
  ('Cristel', 1, 'eV9axCdo11', 'Individual'),
  ('Ramon', 1, 'F1Rpbw27QL', 'Individual'),
  ('Desiree', 1, 'rkSmByvNuH', 'Individual'),
  ('Alejandra', 1, '6y8H5sw2ld', 'Individual'),
  ('Nahomi', 1, '60FwmQHnEQ', 'Individual'),
  ('Santiago', 1, 'EF9OPljwBB', 'Individual'),
  ('Cristian', 1, '1pi9Lk04id', 'Individual'),
  ('Jollet', 1, 'WJESmu32BU', 'Individual'),
  ('Axel', 1, 'p4RGd3zOHY', 'Individual');
